import type { Metadata, Viewport } from "next";
import { Crimson_Pro, Zhi_Mang_Xing } from "next/font/google";
import "./globals.css";

const crimsonPro = Crimson_Pro({
  variable: "--font-crimson-pro",
  subsets: ["latin"],
});

const zhiMangXing = Zhi_Mang_Xing({
  variable: "--font-zhi-mang-xing",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Daniel Chen",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${crimsonPro.variable} ${zhiMangXing.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
